### ISSUE TITLE
Close me pls

### ISSUE THREAD

**Issue by TJT-JTJ** [CareyWang/sub-web#46]
Ignore pls

**Comment by TJT-JTJ** [comment]
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - https://doh.pub/dns-query
    - https://rubyfish.cn/dns-query
    - https://139.224.112.177/dns-query
  fallback:
    - https://dns.rubyfish.cn/dns-query
    - https://doh.xeton.dev/dns-query
    - https://dns.wcc.best/dns-query
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
```

is generated but under 'dns: ' 
there should be a line 
'listen: 0.0.0.0:53' 
to make the Clash for Windows UDP TAP adapter connect. Otherwise correct.
